// const example = <?xml version="1.0" encoding="utf-8"?>
<Declaration>
  <KindOfDeclaration>EXC00</KindOfDeclaration>
  <TypeOfDeclaration>EXC002BG</TypeOfDeclaration>
  <IsCorrectionDeclaration>false</IsCorrectionDeclaration>
  <IsDelayedReporting>false</IsDelayedReporting>
  <PreparationDate>10022022</PreparationDate>
  <CustomsOffice>BG003000</CustomsOffice>
  <TotalAmountOfExciseDuty>00.00</TotalAmountOfExciseDuty>
  <Customer>
    <LegalEntity>SFW</LegalEntity>
    <SIC>202785207</SIC>
    <ExciseNumber>BG003100B0010</ExciseNumber>
  </Customer>
  <Declarer>
    <Name>КАМЕН НИКОЛОВ КОЕВ</Name>
    <Egn>7306241400</Egn>
  </Declarer>
  <ReportingPeriod>
    <TaxPeriod>
      <Start>01012022</Start>
      <End>31012022</End>
    </TaxPeriod>
  </ReportingPeriod>
  <AppliedDocuments>
    <AppliedDocument>
      <DocumentType>40</DocumentType>
      <Description>Акцизни данъчни документи - 14 бр.</Description>
      <DocumentNumber>от № 985 до № 998</DocumentNumber>
      <DocumentDate>31012022</DocumentDate>
    </AppliedDocument>
  </AppliedDocuments>
  <ExciseGoods>
    <ExciseGood>
      <SequenceNumber>1</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>РОЗЕ</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042180</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>05</AdditionalCode>
      <QuantityOfGoods>4.5000</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>0.750</Pieces>
      <NumberOfPackages>6</NumberOfPackages>
      <TaxBase>4.5000</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>2</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>СИРА</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042180</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>03</AdditionalCode>
      <QuantityOfGoods>18.00</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>0.750</Pieces>
      <NumberOfPackages>24</NumberOfPackages>
      <TaxBase>18.00</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>3</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>IMAGE ЧЕРВЕН</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042180</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>21</AdditionalCode>
      <QuantityOfGoods>6.75</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>0.750</Pieces>
      <NumberOfPackages>9</NumberOfPackages>
      <TaxBase>6.75</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>4</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>ТАМЯНКА</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042179</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>17</AdditionalCode>
      <QuantityOfGoods>11.25</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>0.750</Pieces>
      <NumberOfPackages>15</NumberOfPackages>
      <TaxBase>11.25</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>5</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>МУСКАТ</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042179</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>30</AdditionalCode>
      <QuantityOfGoods>4.5</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>0.750</Pieces>
      <NumberOfPackages>6</NumberOfPackages>
      <TaxBase>4.5</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>6</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>КАБЕРНЕ ФРАН</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042180</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>16</AdditionalCode>
      <QuantityOfGoods>8.25</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>0.750</Pieces>
      <NumberOfPackages>11</NumberOfPackages>
      <TaxBase>8.25</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>7</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>КАБЕРНЕ СОВИНЬОН</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042180</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>02</AdditionalCode>
      <QuantityOfGoods>9</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>0.750</Pieces>
      <NumberOfPackages>12</NumberOfPackages>
      <TaxBase>9</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>8</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>МЕРЛО</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042180</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>01</AdditionalCode>
      <QuantityOfGoods>4.5</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>0.750</Pieces>
      <NumberOfPackages>6</NumberOfPackages>
      <TaxBase>4.5</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>9</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>МАЛБЕК</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042180</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>31</AdditionalCode>
      <QuantityOfGoods>13.5</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>0.750</Pieces>
      <NumberOfPackages>18</NumberOfPackages>
      <TaxBase>13.5</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>10</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>СОВ. БЛАН</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042179</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>27</AdditionalCode>
      <QuantityOfGoods>4.5</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>0.750</Pieces>
      <NumberOfPackages>6</NumberOfPackages>
      <TaxBase>4.5</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>11</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>ВИОНИЕ</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042279</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>07</AdditionalCode>
      <QuantityOfGoods>15</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>3</Pieces>
      <NumberOfPackages>5</NumberOfPackages>
      <TaxBase>15</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>12</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>МУСКАТ</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042279</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>30</AdditionalCode>
      <QuantityOfGoods>42</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>3</Pieces>
      <NumberOfPackages>14</NumberOfPackages>
      <TaxBase>42</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>13</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>РОЗЕ</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042280</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>05</AdditionalCode>
      <QuantityOfGoods>15</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>3.000</Pieces>
      <NumberOfPackages>5</NumberOfPackages>
      <TaxBase>15</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>14</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>МЕРЛО</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042280</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>01</AdditionalCode>
      <QuantityOfGoods>54</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>3.000</Pieces>
      <NumberOfPackages>18</NumberOfPackages>
      <TaxBase>54</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>15</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>КАБЕРНЕ СОВИНЬОН</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042280</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>02</AdditionalCode>
      <QuantityOfGoods>93</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>3.000</Pieces>
      <NumberOfPackages>31</NumberOfPackages>
      <TaxBase>93</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>16</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>СИРА</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042280</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>03</AdditionalCode>
      <QuantityOfGoods>189</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>3.000</Pieces>
      <NumberOfPackages>63</NumberOfPackages>
      <TaxBase>189</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>17</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>МАВРУД</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042280</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>04</AdditionalCode>
      <QuantityOfGoods>27</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>3.000</Pieces>
      <NumberOfPackages>9</NumberOfPackages>
      <TaxBase>27</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>18</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>МАЛБЕК</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042280</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>31</AdditionalCode>
      <QuantityOfGoods>12</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>3.000</Pieces>
      <NumberOfPackages>4</NumberOfPackages>
      <TaxBase>12</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>19</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>ШАРДОНЕ</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042279</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>09</AdditionalCode>
      <QuantityOfGoods>21</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>3.000</Pieces>
      <NumberOfPackages>7</NumberOfPackages>
      <TaxBase>21</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>20</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>РОЗЕ</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042180</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>05</AdditionalCode>
      <QuantityOfGoods>36</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>1</Pieces>
      <NumberOfPackages>36</NumberOfPackages>
      <TaxBase>36</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>21</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>МЕРЛО</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042180</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>01</AdditionalCode>
      <QuantityOfGoods>12</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>1</Pieces>
      <NumberOfPackages>12</NumberOfPackages>
      <TaxBase>12</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>22</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>ВИОНИЕ</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042179</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>07</AdditionalCode>
      <QuantityOfGoods>36</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>1</Pieces>
      <NumberOfPackages>36</NumberOfPackages>
      <TaxBase>36</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>23</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>КАБЕРНЕ СОВИНЬОН</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042180</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>02</AdditionalCode>
      <QuantityOfGoods>6</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>1</Pieces>
      <NumberOfPackages>6</NumberOfPackages>
      <TaxBase>6</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>24</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>ШАРДОНЕ</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042179</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>09</AdditionalCode>
      <QuantityOfGoods>6</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>1</Pieces>
      <NumberOfPackages>6</NumberOfPackages>
      <TaxBase>6</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>25</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>МУСКАТ</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042279</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>30</AdditionalCode>
      <QuantityOfGoods>140</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>5</Pieces>
      <NumberOfPackages>28</NumberOfPackages>
      <TaxBase>140</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>26</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>КАБЕРНЕ СОВИНЬОН</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042280</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>02</AdditionalCode>
      <QuantityOfGoods>10</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>5</Pieces>
      <NumberOfPackages>2</NumberOfPackages>
      <TaxBase>10</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>27</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>МАВРУД</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042280</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>04</AdditionalCode>
      <QuantityOfGoods>20</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>5</Pieces>
      <NumberOfPackages>4</NumberOfPackages>
      <TaxBase>20</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
    <ExciseGood>
      <SequenceNumber>28</SequenceNumber>
      <BrandName>A81304</BrandName>
      <Trademark>РОЗЕ</Trademark>
      <APCode>W200</APCode>
      <CNCode>22042280</CNCode>
      <Measure>3</Measure>
      <AdditionalCode>05</AdditionalCode>
      <QuantityOfGoods>10</QuantityOfGoods>
      <IntendedUseOfProduct>401</IntendedUseOfProduct>
      <Purpose>C01</Purpose>
      <DutyAmount>0.00</DutyAmount>
      <Payment>10</Payment>
      <PaidDuty>0.00</PaidDuty>
      <Pieces>5</Pieces>
      <NumberOfPackages>2</NumberOfPackages>
      <TaxBase>10</TaxBase>
      <ExciseDuty>0.000000</ExciseDuty>
    </ExciseGood>
  </ExciseGoods>
</Declaration>